# Rename this file application.yml (figaro gem) .. Already ignored in .gitignore
# Personalize your configuration values + your production dashboard (eg Heroku)

## Google Resources
#
# https://cloud.google.com/identity/docs/verify-domain-web
# https://www.google.com/webmasters/verification/details?hl=en&siteUrl=<YOUR_SITE_URL>
#
# https://www.google.com/webmasters/verification/home?hl=en
#
# https://console.cloud.google.com/apis/credentials/key/<YOUR_KEY>?project=api-project-<YOUR_PROJECT_KEY>
# https://console.cloud.google.com/home/dashboard?project=api-project-<YOUR_PROJECT_KEY>


MAP_KEY: LONG_STRING

GEOCODER_API: LONG_STRING
GEOCODER_API: LONG_STRING

GMAIL_USERNAME: your_name@example.com
GMAIL_PASSWORD: your_password

## Twilio Resources
#
# https://elements.heroku.com/buttons/hashobject/twilio-stun-turn
# https://www.twilio.com/docs/video

TWILIO_ACCOUNT_SID: LONG_STRING
TWILIO_AUTH_TOKEN:  LONG_STRING


## Heroku Config Variables (5 above included below)

# DATABASE_URL

# GEOCODER_API

# MAP_KEY

# GMAIL_PASSWORD

# GMAIL_USERNAME

# LANG

# PAPERTRAIL_API_TOKEN

# RACK_ENV

# RAILS_ENV

# RAILS_LOG_TO_STDOUT

# RAILS_SERVE_STATIC_FILES

# REDIS_TLS_URL

# REDIS_URL

# ROLLBAR_ACCESS_TOKEN

# ROLLBAR_ENDPOINT

# SECRET_KEY_BASE

# TWILIO_ACCOUNT_SID

# TWILIO_AUTH_TOKEN
