# Rename this file application.yml (figaro) .. Already ignored in .gitignore
# Personalize your configuration values here + your production dashboard (eg Heroku)


GMAIL_USERNAME: rrb@example.com
GMAIL_PASSWORD: eadfngyjkoveasplm

TWILIO_ACCOUNT_SID: CRc75df1159399rrbbf3b6666b2f5c59yy
TWILIO_AUTH_TOKEN: 99cub7795f7b1bf1337ee2k535317797


## Heroku Config Variables

# DATABASE_URL

# GEOCODER_API

# GMAIL_PASSWORD

# GMAIL_USERNAME

# LANG

# PAPERTRAIL_API_TOKEN

# RACK_ENV

# RAILS_ENV

# RAILS_LOG_TO_STDOUT

# RAILS_SERVE_STATIC_FILES

# REDIS_TLS_URL

# REDIS_URL

# ROLLBAR_ACCESS_TOKEN

# ROLLBAR_ENDPOINT

# SECRET_KEY_BASE

# TWILIO_ACCOUNT_SID

# TWILIO_AUTH_TOKEN
